### PR TITLE
Created QuestionAnswerService

### PR DESCRIPTION
**Pull request by ShohsanamAbdujabborova**

### CODE REVIEW

**Comment by ShohsanamAbdujabborova** [comment]
Created QuestionAnswerService

**Review by makhammadsoliyev — CHANGES_REQUESTED** [review]
image

**Comment by ShohsanamAbdujabborova** [comment]
Updated QuestionAnswerService

**Comment by ShohsanamAbdujabborova** [comment]
Some changes were with QuestionAnswerService

**Pull request closed without merging**
